### ISSUE TITLE
Does the installer download the latest version or a predefined version?

### ISSUE THREAD

**Issue by karanrajpal14** [source-foundry/Hack-windows-installer#10]
Hey,
Just wanted to know if the installer always downloads the latest version of Hack or downloads a predefined version? It's been a while since you've updated the installer which is why I had to confirm this.

**Comment by chrissimpkins** [comment]
We update this with the latest release version. The current version of Hack is installed.

**Comment by texhex** [comment]
@karanrajpal14: Just for clarification.

1) The installer is updated as soon as either there is a change to the installation process (installer bug fix etc.) or there is a new [release of Hack](https://github.com/texhex/Hack/releases). Each [release of the Hack Windows Installer](https://github.com/source-foundry/Hack-windows-installer/releases) lists what was changed in the given release.

2) The installer is also designed to be used in Enterprise Deployments (install on 5000+ machines). For this, the installer must operate in a deterministic way, means it always does the same thing so it can be tested. If we would try to always download the newest version automatically, this would not work because what is deployed is different from what was tested. Therefore, it does not download any newer version.

3) We are looking into the topic to provide an installer for development builds, so you can get the newest version @chrissimpkins is currently working on by using an installer. I can't give you an ETA for that.
