### ISSUE TITLE
VirusTotal eGambit detecting Issue with installer

### ISSUE THREAD

**Issue by Sasquatch99** [source-foundry/Hack-windows-installer#13]
When looking at the VirsutTotal Report, for the current Windows installer, VirusTotal gives a warning from eGambit. File version 1.4.1 
"eGambit Unsafe.AI_Score_96%"

**Comment by texhex** [comment]
@Sasquatch99 Thanks for the notice, but there is little to nothing we could do. It seems VirusTotal is always having at least one AV software that detects something. 

For v1.2.0 and earlier Qihoo-360 was [the one](https://virustotal.com/en/file/d566623369d830afa7e4680ffdee13a2aac2b739fd58725a79ea793eabdb1428/analysis/1462988182/) that thought the EXE is dangerous. As of now, it was often Cylance (but they seem to be rather fast to update their mathematical model behind) and now it's eGambit that doesn't like us. 

I'm guessing it's because we are using InnoSetup that is freely available and sometimes to use to bundle adware and other crap.

**Comment by texhex** [comment]
@Sasquatch99 It seems eGambit have updated their signatures, the newest report for 1.4.1 has again a zero detection rate: https://www.virustotal.com/#/file/29f73e7a57c0a33c01f7154178d36154aab2c1cfc26f386989ea0aab65db73b5/detection

The new release v1.4.2 is also at zero detections. 

I will close this issue now, please feel free to reopen it if you think this requires more actions.
